import localFont from "next/font/local";
import "./globals.css";
import WhatsAppLive from "./components/WhatsAppLive";
import Navbar from "./components/navbar";
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <div className="relative">
        {children}
        <div className="fixed right-10 top-[600px] z-10 ">
          <WhatsAppLive/>
        </div>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
